### ISSUE TITLE
irssi goes nuts with stalker 0.73

### ISSUE THREAD

**Issue by ivers** [symkat/Stalker#3] opened 2011-08-24 18:45 UTC
After some time (from an hour til a day) irssi goes nuts after loading stalker 0.73.
It duplicates lines, removes input and you cant switch window. You have to detach screen
and kill the process to regain control. What's happening ? :/

**Comment by IsaacG** [comment] 2011-08-24 19:18
Hard to say without some sort of trace... I haven't had any issues myself. I'm going to play with increasing the debug output so we can get a trace of the issue. Do you notice anything that triggers this behavior?

**Comment by IsaacG** [comment] 2011-08-24 20:16
Try downloading the latest version and `/set stalker_log ON`
Hopefully it won't die again and, if it does, we'll have a better clue where it blew up.

**Comment by ivers** [comment] 2011-08-24 20:26
I will reply with the error as soon as it occours. Thank you.

**Comment by ivers** [comment] 2011-08-25 08:09
We have tested this for a few hours now. There is no error in the log, but it has come to our knowledge that stalker spawns a new irssi process that makes it go nuts. When killing that process it spaws it returns to normal.

**Comment by ivers** [comment] 2011-08-25 08:16
10:01 -!- Irssi: Error in script stalker:
10:01 DBD::SQLite::st execute failed: file is encrypted or is not a database at /home/ek/.irssi/scripts/stalker.pl line 368.

I guess this is the reason it can't kill the child process that makes irssi go nuts.

**Comment by elling** [comment] 2011-08-25 08:17
In addition, we get "10:01 -!- Irssi: Error in script stalker:
10:01 DBD::SQLite::st execute failed: file is encrypted or is not a database at /home/ek/.irssi/scripts/stalker.pl line 368." once in a while (i.e. when it crashes and fails to finish whatever the child process is doing).

The last lines in the debug log when it crashed during a join on a big channel is:

[info] [08/25/11 09:58:41] Queue record to add to DB and, if needed, start child process.
[info] [08/25/11 09:58:41] Recursion Level: 0
[info] [08/25/11 09:58:41] Recursion Level: 1
[info] [08/25/11 09:58:41] host query for records on 221.80-202-96.nextgentel.com from server irc.homelien.no returned: 221.80-202-96.nextgentel.com
[info] [08/25/11 09:58:56] Child process complete. Make new child if needed.
[info] [08/25/11 09:58:56] Adding to DB: nick = Castaneda, user = ~Castaneda, host = 221.80-202-96.nextgentel.com, serv = irc.homelien.no
[info] [08/25/11 09:58:56] Added record for Castaneda!~Castaneda@221.80-202-96.nextgentel.com to irc.homelien.no
[info] [08/25/11 09:58:56] Child process complete. Make new child if needed.
[info] [08/25/11 10:01:23] Queue record to add to DB and, if needed, start child process.
[info] [08/25/11 10:01:23] Recursion Level: 0

**Comment by elling** [comment] 2011-08-25 11:46
irssi version 0.8.15 btw :), perl 5.8.9, fbsd 8.2 amd64. Dunno what Ivers uses on his side, but I imagine its some linux stuff..

**Comment by IsaacG** [comment] 2011-08-25 17:40
I think that line 368 issue may be slightly different/unrelated... _shrugs_ I pushed a commit that adds a more detailed message when it dies on that line to include PID, PPID, $child_running and other hopefully useful info.
If you pull that version and get error again, you can check the command of the pid using ps. `ps -p 21543` should show the CMD that pid 21543 is.

As for irssi going nuts, I suspect it has something to do with the fork()ed process receiving events before dying (like a RECONN) that causes it to go off somewhere else and not die like we want it to. Hopefully some sleep()s can be tossed into a fork()ed process and mixed with RECONNs to test/debug this issue.

**Comment by elling** [comment] 2011-08-25 20:09
Crashed again after a while. Last few lines in the log file are:

[info] [08/25/11 21:52:29] Added record for Charlotte!~Charlotte@202.79-160-153.customer.lyse.net to irc.homelien.no
[info] [08/25/11 21:52:29] Adding to DB: nick = morty, user = ~morty, host = 16.225.34.95.customer.cdi.no, serv = irc.homelien.no
[info] [08/25/11 21:52:29] Added record for morty!~morty@16.225.34.95.customer.cdi.no to irc.homelien.no
[info] [08/25/11 21:52:29] Child process complete. Make new child if needed.

Irssi error message:

20:15 DBD::SQLite::st execute failed: database disk image is malformed at /home/ek/.irssi/scripts/stalker.pl line 366

Before this test, i pointed the script at an non-existent db, so its all fresh and new.

The crash left irssi unusable (screen / input is garbled), and a stale irssi child process. Killing that solved the issues in irssi.

there's no crash message in the log, no pid or anything there.

**Comment by IsaacG** [comment] 2011-08-25 20:35
Thanks for your patience and working with me.

Looks like adding PIDs to the die() message was dumb. DBI doesn't return undef on failure when RaiseError is set.

I'm still thinking the issue is the child process responding to some event it shouldn't be responding to. To prevent the child from accessing the DB I removed the signals and binding that allow it to get there. Try the latest commit and tell me if it helps?

**Comment by elling** [comment] 2011-08-25 20:45
On it :)

**Comment by elling** [comment] 2011-08-25 20:53
22:45 DBD::SQLite::st execute failed: file is encrypted or is not a database at /home/ek/.irssi/scripts/stalker.pl line 377.
22:45
22:45 -!- Irssi: Error in script stalker:
22:45 DBD::SQLite::st execute failed: file is encrypted or is not a database at /home/ek/.irssi/scripts/stalker.pl line 377.

Same as before. Nothing helpful in the log or the debug messages. Leaves a stale irssi process, killing it resolves issues whithin irssi. The error is provoked by joining a rather big channel then leaving.

Last log lines:

[info] [08/25/11 22:44:39] Child process complete. Make new child if needed.
[info] [08/25/11 22:45:11] Queue record to add to DB and, if needed, start child process.
[info] [08/25/11 22:45:11] Recursion Level: 0
[info] [08/25/11 22:45:11] Adding to DB: nick = mokja, user = ~MK, host = 238-44-15.connect.netcom.no, serv = irc.homelien.no
[info] [08/25/11 22:45:11] Recursion Level: 1
[info] [08/25/11 22:45:11] host query for records on 238-44-15.connect.netcom.no from server irc.homelien.no returned: 238-44-15.connect.netcom.no
[info] [08/25/11 22:45:11] Added record for mokja!~MK@238-44-15.connect.netcom.no to irc.homelien.no
[info] [08/25/11 22:45:11] Child process complete. Make new child if needed.

**Comment by elling** [comment] 2011-08-25 20:58
After the crash, stalker reports a new error the first time it tries to access the db (or so it seems):

22:51 -!- Irssi: stalker Debug: Stat database.
22:51 -!- Irssi: Loaded stalker
22:51 -!- Irssi: Loaded script stalker
22:51 DBD::SQLite::db prepare failed: file is encrypted or is not a database at /home/ek/.irssi/scripts/stalker.pl line 376.
22:51
22:51 -!- Irssi: Error in script stalker:
22:51 DBD::SQLite::db prepare failed: file is encrypted or is not a database at /home/ek/.irssi/scripts/stalker.pl line 376.

This leaves irssi "dead" until i kill the child process.

**Comment by IsaacG** [comment] 2011-08-25 21:48
Yay! I got that error! Doing a lookup in the parent while the child is busy adding records will do it.

**Comment by IsaacG** [comment] 2011-08-25 23:47
Fixed maybe possibly?
Latest push adds:
 # Magic bullt that fixes read/write conflicts
 # Requires sqlite 2.7.0 or newer
 # Has no affect on older versions
 # See http://www.sqlite.org/draft/wal.html
 $DBH->do( "PRAGMA journal_mode=WAL;" );

**Comment by IsaacG** [comment] 2011-08-25 23:49
Hrm. Disregard. Going try making a second DBH and seeing if that helps...

**Comment by elling** [comment] 2011-08-26 08:42
Testing the new version now, so far so good..

**Comment by IsaacG** [comment] 2011-08-26 18:09
(There is a "testing" branch which has two DBH's so both processes are not using the same filehandles or whatever. I branched to stop mucking up the main branch. Hopefully we can fix everything up in testing then merge changes into the main branch. Feedback appreciated!)

**Comment by elling** [comment] 2011-08-29 06:42
So far it seems stable, left it running over the weekend whitout any problems.

**Comment by IsaacG** [comment] 2011-09-07 18:23
Gonna assume it's all fixed now :D

**Closed as completed** 2011-12-12 19:40 UTC
